[metadata]
name = quannet
version = attr: quannet.__version__

[options]
package_dir =
    = src
packages = find:
install_requires =
    pandas == 1.3.3
    torch == 2.0.1
    scikit-learn == 1.3.0
    tqdm == 4.66.1
    biopython == 1.79
    pdb2pqr == 3.4.1

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    quannet = quannet.config:entrypoint

[flake8]
max-line-length = 121
docstring-convention = google
exclude = APBS-3.4.1.Linux,
application-import-names = quannet
import-order-style = pycharm

[isort]
profile=black
line_length=121
skip_gitignore=True
known_first_party=quannet
known_third_party=pandas,torch,biopython
no_lines_before=LOCALFOLDER
sections=FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
