# General Settings
mode: predict  # Mode for QuanNet (e.g., 'train', 'predict')
docker_image: quannet:latest  # docker image tag where to prepare model inputs

# Optional Experiment Details
project: # Project name (optional)
name:  # Experiment name (optional, results saved in 'project/name' directory)

# Prediction Settings
structures:  # Source directory for PDB structures
model:  # Path to pre-trained model file (e.g., 'quannet.pt')

# Training Settings
dataset:  # The directory path to the dataset, which includes both the structural data files
          # and a CSV table mapping each structure to its corresponding target values.
grid_dim: 96  # Number of grid points along each axis
grid_spacing: 0.75  # Spacing between grid points (in Angstroms)
shell_width: 2.0  # Thickness of surface shell (in Angstroms)
num_augmentations: 5  # Number of data augmentations
remove_artefacts: true  # Flag to remove artefacts
precomputed_input: false  # Flag to use precomputed inputs
lr: 0.0001  # Learning rate
weight_decay: 0.00001 # L2 regularization
deterministic: true  # Flag for deterministic training
processes: 4  # Number of processes
val_size: 0.2  # Fraction of data for validation
max_bins_stratify: 5  # Max number of bins for stratified train-val split
batch_size: 4  # Batch size
max_epochs: 3  # Maximum number of epochs

# Checkpoint and Device Settings
resume: false  # Flag to resume training from last checkpoint
exist_ok: false  # Flag to overwrite existing experiment
accelerator: auto  # Accelerator type ('cpu', 'gpu', etc.), used in Lightning's Trainer
devices: auto  # Devices to use (str | int | list[int]), used in Lightning's Trainer
every_n_train_steps:  # Steps between checkpoints (optional), used in Lightning's ModelCheckpoint

# Data Column Names
path_csv_col: path  # Column name for paths in CSV
target_csv_col: target  # Column name for targets in CSV

# Custom config.yml
config:  # Path to custom config file for overriding this one (optional)
