# Default training settings and hyperparameters
mode: train  # (str) QuanNet mode, i.e. train, val, predict
data:  # (str, optional) CSV file with structure paths

# Train settings -------------------------------------------------------------------------------------------------------
model:  # (str, optional) path to model file, i.e. quannet.pt
grid_dim: 96  # (int) number of grid points along all 3 axes
grid_spacing: 0.75  # (float) spacing between grid points in Angstroms
shell_width: 2.0  # (float) thickness of the surface shell in Angstroms
num_augmentations: 10  # (int) augmentation level

deterministic: True
processes: 4
output_dir:
val_size: 0.2
bins: 5
batch_size: 10

dirpath: runs  # (str) directory to save the model file relative to root or an absolute path
accelerator: auto  # (str) "cpu", "gpu", etc., refer to accelerator param in lightning.pytorch.Trainer
devices: auto  # (str | int | list[int]) the devices to use, refer to devices param in lightning.pytorch.Trainer

# Prediction settings --------------------------------------------------------------------------------------------------
source:  # (str) source directory for PDB structures

# Custom config.yaml ---------------------------------------------------------------------------------------------------
config:  # (str, optional) for overriding default.yaml
