ENTITY_KEY = 'Entity'
VISCOSITY_KEY = 'Viscosity_at_150'

ESP_GRID_KEY = 'esp_grid'
INPUT_MOL_KEY = 'input_mol'
ROT_X_KEY = 'rot_x'
ROT_Y_KEY = 'rot_y'
ROT_Z_KEY = 'rot_z'
GRID_SPACING_KEY = 'grid_spacing'
GRID_DIM_KEY = 'grid_dim'
SHELL_WIDTH_KEY = 'shell_width'
NUM_AUGMENTATIONS_KEY = 'num_augmentations'
PROCESSES_KEY = 'processes'
HOMOLOGY_DIR_KEY = 'homology_dir'
LEARNING_RATE_KEY = 'learning_rate'
MAX_EPOCHS_KEY = 'max_epochs'
BATCH_SIZE_KEY = 'batch_size'
VERBOSE_KEY = 'verbose'
MODEL_STATE_DICT_KEY = 'model_state_dict'
NUB_BINS_KEY = 'bins'
VAL_SIZE_KEY = 'val_size'
COL_PATH = 'path'
COL_TARGET = 'target'

LEARNING_RATE = 1e-6
MAX_EPOCHS = 10
BATCH_SIZE = 1
PROCESSES = 4
VERBOSE = 0
NUB_BINS = 5
VAL_SIZE = 0.1


DEFAULT_GRID_PARAMS = {
    GRID_DIM_KEY: 96,
    GRID_SPACING_KEY: 0.75,
    SHELL_WIDTH_KEY: 2.0,
    NUM_AUGMENTATIONS_KEY: 10,
}

DEFAULT_TRAIN_PARAMS = {
    **DEFAULT_GRID_PARAMS,
    LEARNING_RATE_KEY: LEARNING_RATE,
    MAX_EPOCHS_KEY: MAX_EPOCHS,
    BATCH_SIZE_KEY: BATCH_SIZE,
    PROCESSES_KEY: PROCESSES,
    VERBOSE_KEY: VERBOSE,
    NUB_BINS_KEY: NUB_BINS,
    VAL_SIZE_KEY: VAL_SIZE,
}

DEFAULT_PREDICT_PARAMS = {
    **DEFAULT_GRID_PARAMS,
    BATCH_SIZE_KEY: BATCH_SIZE,
    PROCESSES_KEY: PROCESSES,
    VERBOSE_KEY: VERBOSE,
}
